services:
  db:
    container_name: mongo-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  api:
    container_name: express-api
    build:
      context: .
      dockerfile: Docker/api-rest/Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://admin:admin@db:27017/
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Docker/app/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  mongo_data:
    driver: local